export {default as Register} from './Register/Register';
export {default as Login} from './Login/Login';
export {default as UserProfile} from './UserProfile/UserProfile';
export {default as Home} from './Home/Home';
export {default as BlogView} from './BlogView/BlogView';
export {default as WriteBlog} from './WriteBlog/WriteBlog';
export {default as Homedoctor} from './Homedoctor/Homedoctor';
export {default as AppointmentForm} from './AppointmentForm/AppointmentForm';
export {default as AppointmentDetails} from './AppointmentDetails/AppointmentDetails';
